import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../core/contacts/contact_service.dart';
import '../core/identity/identity_service.dart';

// ── InvitePayload ─────────────────────────────────────────────────────────────

/// The data embedded in every invite — owner identity + expiry.
///
/// Encoded as base64url JSON for QR codes and deep-links.
/// The human-readable [displayCode] (`NEXUS-XXXX-XXXX`) is a short label
/// derived from the raw 8-char [code].
class InvitePayload {
  final String code;      // raw 8-char key, e.g. "A7K3M9PX"
  final String did;
  final String pseudonym;
  final String xpub;      // X25519 public key hex
  final String npub;      // Nostr public key hex
  final DateTime expires;

  const InvitePayload({
    required this.code,
    required this.did,
    required this.pseudonym,
    required this.xpub,
    required this.npub,
    required this.expires,
  });

  /// Human-readable display code, e.g. `NEXUS-A7K3-M9PX`.
  String get displayCode =>
      'NEXUS-${code.substring(0, 4)}-${code.substring(4, 8)}';

  bool get isExpired => DateTime.now().isAfter(expires);

  // ── Encoding ──────────────────────────────────────────────────────────────

  Map<String, dynamic> _toJson() => {
        'c': code,
        'd': did,
        'p': pseudonym,
        'x': xpub,
        'n': npub,
        'e': expires.millisecondsSinceEpoch,
      };

  /// Base64url-encoded JSON representation for QR codes / deep-links.
  String get encoded =>
      base64Url.encode(utf8.encode(json.encode(_toJson())));

  /// Decodes a base64url-encoded payload. Returns null on any error.
  static InvitePayload? tryDecode(String encoded) {
    try {
      // Pad if necessary (base64url omits trailing '=')
      final padded = encoded.padRight(
        encoded.length + (4 - encoded.length % 4) % 4,
        '=',
      );
      final bytes = base64Url.decode(padded);
      final map = json.decode(utf8.decode(bytes)) as Map<String, dynamic>;
      return InvitePayload(
        code: map['c'] as String,
        did: map['d'] as String,
        pseudonym: map['p'] as String,
        xpub: map['x'] as String,
        npub: map['n'] as String,
        expires: DateTime.fromMillisecondsSinceEpoch(map['e'] as int),
      );
    } catch (_) {
      return null;
    }
  }

  /// Normalises a typed display code to the raw 8-char code.
  /// Accepts `NEXUS-A7K3-M9PX`, `A7K3M9PX`, `nexus-a7k3-m9px`, etc.
  static String normaliseCode(String display) =>
      display.replaceAll(RegExp(r'[^A-Za-z0-9]'), '').toUpperCase();

  /// Returns true when [normalised] (8 uppercase alphanumeric chars) has the
  /// correct length and alphabet.
  static bool isValidCode(String normalised) =>
      RegExp(r'^[A-Z0-9]{8}$').hasMatch(normalised);
}

// ── InviteRecord ──────────────────────────────────────────────────────────────

/// A locally-stored record of an invite that was generated by this user.
class InviteRecord {
  final String code;           // raw 8 chars
  final String encoded;        // base64url payload
  final DateTime createdAt;
  String? redeemedByPseudonym; // null = still pending

  InviteRecord({
    required this.code,
    required this.encoded,
    required this.createdAt,
    this.redeemedByPseudonym,
  });

  String get displayCode =>
      'NEXUS-${code.substring(0, 4)}-${code.substring(4, 8)}';

  bool get isPending => redeemedByPseudonym == null;

  Map<String, dynamic> toJson() => {
        'code': code,
        'encoded': encoded,
        'createdAt': createdAt.toIso8601String(),
        if (redeemedByPseudonym != null) 'redeemedBy': redeemedByPseudonym,
      };

  factory InviteRecord.fromJson(Map<String, dynamic> m) => InviteRecord(
        code: m['code'] as String,
        encoded: m['encoded'] as String,
        createdAt: DateTime.parse(m['createdAt'] as String),
        redeemedByPseudonym: m['redeemedBy'] as String?,
      );
}

// ── RedeemResult ──────────────────────────────────────────────────────────────

/// Result returned by [InviteService.redeemCode].
class RedeemResult {
  final bool success;
  final String? inviterPseudonym;
  final String? error;

  const RedeemResult.ok(this.inviterPseudonym) : success = true, error = null;
  const RedeemResult.fail(this.error)
      : success = false,
        inviterPseudonym = null;
}

// ── InviteService ─────────────────────────────────────────────────────────────

/// Manages invite-code generation, sharing, redemption and status tracking.
///
/// Invite codes (format `NEXUS-XXXX-XXXX`) encode the inviter's DID, keys,
/// and pseudonym in a base64url payload.  The full payload is embedded in the
/// QR / share-link so the invitee never needs a network round-trip to decode.
class InviteService {
  static final instance = InviteService._();
  InviteService._();

  static const _prefsKey = 'nexus_invites';
  static const _alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  static const _validityDays = 30;

  // Fallback GitHub releases page when the API is unreachable.
  static const _releasesUrl =
      'https://github.com/project-nexus-official/'
      'N.E.X.U.S.-OneApp-Betriebssystem-der-freien-Welt/releases/latest';

  final List<InviteRecord> _invites = [];

  /// Read-only view of generated invites (most recent first).
  List<InviteRecord> get invites => List.unmodifiable(_invites);

  // ── Persistence ───────────────────────────────────────────────────────────

  Future<void> load() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final raw = prefs.getString(_prefsKey);
      if (raw == null) return;
      final list = json.decode(raw) as List<dynamic>;
      _invites
        ..clear()
        ..addAll(list.map((e) => InviteRecord.fromJson(e as Map<String, dynamic>)));
    } catch (e) {
      debugPrint('[INVITE] load failed: $e');
    }
  }

  Future<void> _save() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(
        _prefsKey,
        json.encode(_invites.map((r) => r.toJson()).toList()),
      );
    } catch (e) {
      debugPrint('[INVITE] save failed: $e');
    }
  }

  // ── Code generation ───────────────────────────────────────────────────────

  /// Generates a new invite code for [did]/[pseudonym]/[xpub]/[npub].
  ///
  /// Stores the record locally and (optionally) publishes a Nostr event via
  /// [publishToNostr] callback (fire-and-forget; failures are ignored).
  Future<InviteRecord> generateInviteCode({
    required String did,
    required String pseudonym,
    required String xpub,
    required String npub,
    Future<void> Function(InvitePayload)? publishToNostr,
  }) async {
    final code = _generateRawCode();
    final payload = InvitePayload(
      code: code,
      did: did,
      pseudonym: pseudonym,
      xpub: xpub,
      npub: npub,
      expires: DateTime.now().add(const Duration(days: _validityDays)),
    );

    final record = InviteRecord(
      code: code,
      encoded: payload.encoded,
      createdAt: DateTime.now(),
    );

    _invites.insert(0, record); // newest first
    await _save();

    // Nostr publish is best-effort — don't block or throw on failure.
    if (publishToNostr != null) {
      publishToNostr(payload).catchError((e) {
        debugPrint('[INVITE] Nostr publish failed (ignored): $e');
      });
    }

    return record;
  }

  // ── Redemption ────────────────────────────────────────────────────────────

  /// Redeems an invite from a deep-link or raw base64url-encoded string.
  ///
  /// Extracts the [InvitePayload], validates expiry, adds the inviter as a
  /// contact (via [ContactService]), and optionally sends a notification DM
  /// back to the inviter via [sendDmNotification].
  ///
  /// Returns [RedeemResult.fail] on any validation error.
  Future<RedeemResult> redeemEncoded({
    required String encoded,
    required String myPseudonym,
    Future<void> Function({
      required String toDid,
      required String message,
    })? sendDmNotification,
  }) async {
    // Accept both raw encoded and deep-link formats.
    final rawEncoded = _extractEncoded(encoded);
    if (rawEncoded == null) {
      return const RedeemResult.fail(
          'Ungültiger Einladungslink. Bitte scanne den QR-Code erneut.');
    }

    final payload = InvitePayload.tryDecode(rawEncoded);
    if (payload == null) {
      return const RedeemResult.fail(
          'Der Einladungscode konnte nicht gelesen werden.');
    }

    if (payload.isExpired) {
      return const RedeemResult.fail(
          'Dieser Einladungscode ist abgelaufen (gültig 30 Tage).');
    }

    // Prevent redeeming own invite.
    final myDid = await _getMyDid();
    if (myDid != null && payload.did == myDid) {
      return const RedeemResult.fail(
          'Du kannst deinen eigenen Einladungscode nicht einlösen.');
    }

    // Add the inviter as a contact.
    try {
      await ContactService.instance.addContactFromQr(
        did: payload.did,
        pseudonym: payload.pseudonym,
        encryptionPublicKey: payload.xpub,
        nostrPubkey: payload.npub,
      );
    } catch (e) {
      debugPrint('[INVITE] addContactFromQr failed: $e');
      // Continue — contact might already exist; that is fine.
    }

    // Notify the inviter (best-effort).
    if (sendDmNotification != null && payload.did.isNotEmpty) {
      sendDmNotification(
        toDid: payload.did,
        message: 'Deine Einladung wurde angenommen von $myPseudonym! '
            'Wir sind jetzt in N.E.X.U.S. verbunden.',
      ).catchError((e) {
        debugPrint('[INVITE] DM notification failed (ignored): $e');
      });
    }

    return RedeemResult.ok(payload.pseudonym);
  }

  // ── Status tracking ───────────────────────────────────────────────────────

  /// Marks an outbound invite (identified by [code]) as redeemed by [byPseudonym].
  Future<void> markRedeemed(String code, String byPseudonym) async {
    final record = _invites.where((r) => r.code == code).firstOrNull;
    if (record == null) return;
    record.redeemedByPseudonym = byPseudonym;
    await _save();
  }

  // ── Share helpers ─────────────────────────────────────────────────────────

  /// Builds the `nexus://invite?c=...&d=...` deep-link.
  String buildDeepLink(InviteRecord record) =>
      'nexus://invite?c=${record.displayCode}&d=${record.encoded}';

  /// Builds the human-readable share text (for native share sheet / chat).
  String buildShareText(
    InviteRecord record, {
    String apkUrl = _releasesUrl,
    String winUrl = _releasesUrl,
  }) {
    final payload = InvitePayload.tryDecode(record.encoded);
    final expiry = payload?.expires;
    final expiryStr = expiry != null
        ? '${expiry.day.toString().padLeft(2, '0')}.'
            '${expiry.month.toString().padLeft(2, '0')}.'
            '${expiry.year}'
        : '30 Tage';

    return 'Ich nutze N.E.X.U.S. — eine App für echte digitale Souveränität. '
        'Dezentral, verschlüsselt, ohne Konzerne.\n\n'
        'Lade die App herunter und gib meinen Einladungscode ein — '
        'dann sind wir sofort verbunden:\n\n'
        'Code: ${record.displayCode}\n'
        '(gültig bis $expiryStr)\n\n'
        'Android: $apkUrl\n'
        'Windows: $winUrl\n\n'
        'Mehr Infos: nexus-terminal.org';
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  static String _generateRawCode() {
    final rng = math.Random.secure();
    return String.fromCharCodes(
      List.generate(
        8,
        (_) => _alphabet.codeUnitAt(rng.nextInt(_alphabet.length)),
      ),
    );
  }

  /// Extracts the base64url-encoded payload from a raw encoded string or
  /// a `nexus://invite?...&d=<encoded>` deep-link.
  static String? _extractEncoded(String input) {
    final trimmed = input.trim();
    if (trimmed.startsWith('nexus://invite')) {
      // Parse as URI
      final uri = Uri.tryParse(trimmed);
      return uri?.queryParameters['d'];
    }
    // Assume raw base64url
    if (trimmed.isNotEmpty) return trimmed;
    return null;
  }

  Future<String?> _getMyDid() async {
    // Test override via SharedPreferences (set in unit tests).
    try {
      final prefs = await SharedPreferences.getInstance();
      final override = prefs.getString('_invite_test_did');
      if (override != null) return override;
    } catch (_) {}
    return IdentityService.instance.currentIdentity?.did;
  }

  /// Resets in-memory state (used in tests only).
  @visibleForTesting
  void resetForTest() {
    _invites.clear();
  }
}
